---
- name: Install Apache
  apt: name=apache2 state=present
  notify: start apache

- name: Php file to check php working or not in apache
  template: src=info.php dest=/var/www/html/info.php mode=0664
   


